const translations = {
"Home":"Inicio","Services":"Servicios","Excursions":"Excursiones","Our Fleet":"Nuestra Flota","About Us":"Nosotros","Leadership":"Liderazgo","Contact":"Contacto","📅 Book Now":"📅 Reservar Ahora",
"Premium Transportation & Excursions":"Transporte Premium y Excursiones","Your Journey.":"Tu Viaje.","Our Priority.":"Nuestra Prioridad.","Safe. Reliable. Comfortable. Always.":"Seguro. Confiable. Cómodo. Siempre.","Airport transfers • Private charters • Excursions • Punta Cana & beyond.":"Traslados al aeropuerto • Transporte privado • Excursiones • Punta Cana y más allá.","Get a Quote →":"Solicitar Cotización →","Explore Services":"Ver Servicios","Book Your Ride":"Reserva Tu Viaje","Airport Transfer":"Traslado al Aeropuerto","Private Transfer":"Traslado Privado","Vehicle Type":"Tipo de Vehículo","Luxury SUV":"SUV de Lujo","Sedan":"Sedán","SUV":"SUV","Luxury Van":"Van de Lujo","Passenger Van":"Van de Pasajeros","Mini Bus":"Minibús","Coach":"Autobús","Airport Transfers":"Traslados al Aeropuerto","Private Transfers":"Traslados Privados","Hourly Charters":"Servicio por Horas","Group Transportation":"Transporte para Grupos","Corporate & VIP":"Corporativo y VIP","Excursions & Tours":"Excursiones y Tours","Accessible Transport":"Transporte Accesible","Weddings & Events":"Bodas y Eventos","The Right Vehicle for Every Journey":"El Vehículo Ideal para Cada Viaje","A flexible mix of black and white vehicles—from executive sedans and luxury SUVs to passenger vans, minibuses and full-size coaches.":"Una flota flexible de vehículos negros y blancos: desde sedanes ejecutivos y SUVs de lujo hasta vans de pasajeros, minibuses y autobuses.","Explore Our Fleet →":"Ver Nuestra Flota →","Unforgettable Experiences":"Experiencias Inolvidables","Discover More Than a Destination":"Descubre Mucho Más que un Destino","Transportation, excursions and guest service throughout Punta Cana and the Dominican Republic.":"Transporte, excursiones y servicio al huésped en Punta Cana y toda la República Dominicana.","Beaches, islands, adventure and cultural experiences—with transportation coordinated from start to finish.":"Playas, islas, aventura y experiencias culturales, con transporte coordinado de principio a fin.","Explore Excursions":"Ver Excursiones","Professional Transportation":"Transporte Profesional","Airport, private, corporate, group and long-distance transportation tailored to your trip.":"Transporte al aeropuerto, privado, corporativo, para grupos y de larga distancia adaptado a tu viaje.","View Services":"Ver Servicios","Accessibility for Everyone":"Accesibilidad para Todos","Accessible transportation and mobility support designed to help more travelers enjoy Punta Cana comfortably.":"Transporte accesible y apoyo de movilidad para que más viajeros disfruten Punta Cana con comodidad.","Accessible Services":"Servicios Accesibles",
"Stellar Routes":"Stellar Routes","Our Services":"Nuestros Servicios","Professional transportation for every journey.":"Transporte profesional para cada viaje.","✈ Airport Transfers":"✈ Traslados al Aeropuerto","PUJ airport pickup and drop-off, meet & greet, flight coordination and luggage assistance.":"Recogida y traslado en el aeropuerto PUJ, recepción, coordinación de vuelos y asistencia con equipaje.","🚙 Private Transportation":"🚙 Transporte Privado","Point-to-point, resort, villa, Airbnb, intercity and dedicated driver transportation.":"Transporte punto a punto, resorts, villas, Airbnb, interurbano y servicio con conductor dedicado.","◷ Hourly Charters":"◷ Servicio por Horas","Hourly, half-day and full-day private vehicle and chauffeur service.":"Vehículo privado con chofer por hora, medio día o día completo.","👥 Group Transportation":"👥 Transporte para Grupos","Vans, Sprinters, minibuses and group transportation for families, tours and events.":"Vans, Sprinters, minibuses y transporte para familias, tours y eventos.","💼 Corporate & VIP":"💼 Corporativo y VIP","Executive airport transportation, meetings, conferences, VIP guests and private aviation coordination.":"Transporte ejecutivo al aeropuerto, reuniones, conferencias, huéspedes VIP y coordinación de aviación privada.","♿ Accessible Transportation":"♿ Transporte Accesible","Transportation and mobility support for wheelchair users, seniors and travelers with limited mobility.":"Transporte y apoyo de movilidad para usuarios de silla de ruedas, adultos mayores y viajeros con movilidad limitada.","📅 Weddings & Events":"📅 Bodas y Eventos","Transportation for couples, wedding parties, guests, celebrations and special events.":"Transporte para parejas, bodas, invitados, celebraciones y eventos especiales.","👶 Family Transportation":"👶 Transporte Familiar","Child seats, boosters, strollers and family-friendly transportation coordination.":"Sillas infantiles, elevadores, cochecitos y coordinación de transporte para familias.","📍 Long-Distance & Intercity":"📍 Larga Distancia e Interurbano","Private transportation beyond Punta Cana to destinations throughout the Dominican Republic.":"Transporte privado desde Punta Cana hacia destinos en toda la República Dominicana.",
"Excursions & Tours":"Excursiones y Tours","Discover the beauty, culture and adventure of the Dominican Republic.":"Descubre la belleza, cultura y aventura de la República Dominicana.","Island & Beach Fun":"Islas y Diversión en la Playa","Saona, Catalina, catamaran cruises, snorkeling, swimming and private beach experiences.":"Saona, Catalina, paseos en catamarán, snorkel, natación y experiencias en playas privadas.","Dune Buggies & Adventure":"Buggies y Aventura","Dune buggies, ATVs, ziplining, caves, cenotes and other high-energy Punta Cana adventures.":"Buggies, ATVs, tirolesa, cuevas, cenotes y otras aventuras llenas de energía en Punta Cana.","Culture & Sightseeing":"Cultura y Recorridos","Santo Domingo, countryside experiences, shopping and customized private sightseeing.":"Santo Domingo, experiencias rurales, compras y recorridos privados personalizados.","Water Experiences":"Experiencias Acuáticas","Snorkeling, catamarans, water activities and unforgettable days on the Caribbean Sea.":"Snorkel, catamaranes, actividades acuáticas y días inolvidables en el Mar Caribe.","Horseback riding and additional excursions are also available by request.":"Paseos a caballo y otras excursiones también están disponibles a solicitud.","Request an Excursion Reservation":"Solicitar Reserva de Excursión",
"Modern vehicle options for individuals, families, VIPs and groups.":"Opciones modernas de vehículos para individuos, familias, VIPs y grupos.","Luxury SUVs":"SUVs de Lujo","Premium comfort for VIPs, couples and small groups.":"Comodidad premium para VIPs, parejas y grupos pequeños.","Sedans & SUVs":"Sedanes y SUVs","Private airport and point-to-point transportation.":"Transporte privado al aeropuerto y punto a punto.","Luxury Vans & Sprinters":"Vans de Lujo y Sprinters","Comfortable service for families and larger parties.":"Servicio cómodo para familias y grupos grandes.","Passenger Vans":"Vans de Pasajeros","Flexible transportation for groups and excursions.":"Transporte flexible para grupos y excursiones.","Minibuses":"Minibuses","Ideal for tours, events, weddings and group travel.":"Ideal para tours, eventos, bodas y viajes en grupo.","Coaches":"Autobuses","High-capacity transportation for conventions and large groups.":"Transporte de alta capacidad para convenciones y grupos grandes.","Vehicle availability and exact models vary by reservation requirements. Black and white vehicle options may be requested based on availability.":"La disponibilidad y los modelos exactos varían según los requisitos de la reserva. Se pueden solicitar vehículos negros o blancos según disponibilidad.",
"About Stellar Routes":"Acerca de Stellar Routes","More Than Transportation":"Más que Transporte","Local expertise. Professional service. A brighter journey.":"Experiencia local. Servicio profesional. Un mejor viaje.","Our Mission":"Nuestra Misión","Provide safe, reliable and personalized transportation and experiences for visitors, residents and business travelers throughout the Dominican Republic.":"Brindar transporte y experiencias seguras, confiables y personalizadas para visitantes, residentes y viajeros de negocios en toda la República Dominicana.","Our Difference":"Nuestra Diferencia","We combine local knowledge, hospitality, modern service standards and accessibility with transportation built around the guest.":"Combinamos conocimiento local, hospitalidad, estándares modernos de servicio y accesibilidad con transporte centrado en cada huésped.","Our Leadership":"Nuestro Liderazgo","Stellar Routes combines Dominican transportation and tourism experience with decades of executive hospitality and business leadership.":"Stellar Routes combina experiencia dominicana en transporte y turismo con décadas de liderazgo ejecutivo en hospitalidad y negocios.","Meet Our Leadership":"Conoce Nuestro Liderazgo",
"Experience. Relationships. Guest Service.":"Experiencia. Relaciones. Servicio al Huésped.","President & Owner":"Presidente y Propietario","Radhames brings decades of experience in transportation, tourism and guest services throughout the Dominican Republic. His extensive knowledge of Punta Cana and the country’s tourism industry comes from years of personally serving travelers, families, groups and private clients.":"Radhames aporta décadas de experiencia en transporte, turismo y servicio al huésped en toda la República Dominicana. Su amplio conocimiento de Punta Cana y de la industria turística del país proviene de años atendiendo personalmente a viajeros, familias, grupos y clientes privados.","As President & Owner of Stellar Routes, he leads transportation operations, guest services and local partnerships with a commitment to safe, reliable, professional and seamless service.":"Como Presidente y Propietario de Stellar Routes, dirige las operaciones de transporte, el servicio al huésped y las alianzas locales, con el compromiso de brindar un servicio seguro, confiable, profesional y sin complicaciones.","Vice President & Co-Owner":"Vicepresidente y Copropietario","Bruce brings more than 45 years of executive leadership across hospitality, casino operations, guest service and international business environments, with extensive experience in operations, business development and strategic partnerships.":"Bruce aporta más de 45 años de liderazgo ejecutivo en hospitalidad, operaciones de casinos, servicio al huésped y entornos empresariales internacionales, con amplia experiencia en operaciones, desarrollo de negocios y alianzas estratégicas.","As Vice President & Co-Owner of Stellar Routes, he supports strategic growth, corporate relationships and the high-touch service standards that distinguish the company in Punta Cana and beyond.":"Como Vicepresidente y Copropietario de Stellar Routes, impulsa el crecimiento estratégico, las relaciones corporativas y los altos estándares de servicio personalizado que distinguen a la empresa en Punta Cana y más allá.",
"Contact Us":"Contáctanos","We’re here to help plan your transportation and Punta Cana experience.":"Estamos aquí para ayudarte a planificar tu transporte y tu experiencia en Punta Cana.","Main:":"Principal:","Cell:":"Celular:","Email:":"Correo:","Location:":"Ubicación:","Punta Cana, Dominican Republic":"Punta Cana, República Dominicana","Book a Reservation":"Reservar","Send Us a Message":"Envíanos un Mensaje","For fastest service, email us directly.":"Para una atención más rápida, escríbenos directamente por correo.","Email Stellar Routes":"Enviar Correo a Stellar Routes",
"Reservations":"Reservas","Book Your Journey":"Reserva Tu Viaje","Send your transportation or excursion request to our team.":"Envía a nuestro equipo tu solicitud de transporte o excursión.","Reservation Request":"Solicitud de Reserva","Service":"Servicio","Private Transportation":"Transporte Privado","Excursion":"Excursión","Corporate / VIP":"Corporativo / VIP","Accessible Transportation":"Transporte Accesible","Wedding / Event":"Boda / Evento","Trip":"Viaje","One Way":"Solo Ida","Round Trip":"Ida y Vuelta","Pickup Location":"Lugar de Recogida","Drop-off Location":"Destino","Pickup Date":"Fecha de Recogida","Pickup Time":"Hora de Recogida","Passengers":"Pasajeros","Flight Number":"Número de Vuelo","Name":"Nombre","Email":"Correo Electrónico","Mobile / WhatsApp":"Móvil / WhatsApp","Accessibility / Child Seat":"Accesibilidad / Silla Infantil","Special Requests":"Solicitudes Especiales","Request Reservation →":"Solicitar Reserva →","Submitting opens your email application with the reservation details addressed to info@StellarRoutes.com. We can switch this to direct server-side delivery once the mailbox/form service is connected.":"Al enviar, se abrirá tu aplicación de correo con los detalles de la reserva dirigidos a info@StellarRoutes.com. Podremos cambiarlo a envío directo cuando se conecte el servicio del formulario.","Need help now?":"¿Necesitas ayuda ahora?","Punta Cana • Dominican Republic":"Punta Cana • República Dominicana"
};
const placeholderTranslations={"✈ Pickup Location":"✈ Lugar de Recogida","📍 Drop-off Location":"📍 Destino","Flight Number":"Número de Vuelo","Name":"Nombre","Email":"Correo Electrónico","Mobile / WhatsApp":"Móvil / WhatsApp","Accessibility / Child Seat":"Accesibilidad / Silla Infantil","Special Requests":"Solicitudes Especiales"};
function translatePage(lang){
 document.documentElement.lang=lang==='es'?'es':'en';
 document.querySelectorAll('body *:not(script):not(style)').forEach(el=>{
   if(el.children.length===0){
     if(!el.dataset.enText) el.dataset.enText=el.textContent;
     const en=el.dataset.enText.trim();
     if(lang==='es' && translations[en]) el.textContent=translations[en];
     else if(lang==='en') el.textContent=el.dataset.enText;
   }
 });
 document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(el=>{
   if(!el.dataset.enPlaceholder) el.dataset.enPlaceholder=el.placeholder;
   el.placeholder=lang==='es'?(placeholderTranslations[el.dataset.enPlaceholder]||el.dataset.enPlaceholder):el.dataset.enPlaceholder;
 });
 const b=document.querySelector('.lang-toggle'); if(b) b.textContent=lang==='es'?'🌐 ES ▾':'🌐 EN ▾';
 localStorage.setItem('stellarLang',lang);
}
document.addEventListener('DOMContentLoaded',()=>{
 const m=document.querySelector('.menu'),l=document.querySelector('.links');if(m)m.onclick=()=>l.classList.toggle('open');
 const langBtn=document.querySelector('.lang-toggle'); if(langBtn) langBtn.addEventListener('click',()=>translatePage((localStorage.getItem('stellarLang')||'en')==='en'?'es':'en'));
 translatePage(localStorage.getItem('stellarLang')||'en');
 const mini=document.querySelector('#miniBooking');if(mini)mini.addEventListener('submit',e=>{e.preventDefault();const p=new URLSearchParams(new FormData(mini));location.href='reservation.html?'+p.toString()});
 const form=document.querySelector('#reservationForm');if(form){const p=new URLSearchParams(location.search);p.forEach((v,k)=>{const el=form.elements[k];if(el)el.value=v});form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);let lines=[];d.forEach((v,k)=>{if(v)lines.push(`${k}: ${v}`)});const subject=encodeURIComponent('Stellar Routes Reservation Request - '+(d.get('name')||'Guest'));const body=encodeURIComponent('New reservation request\n\n'+lines.join('\n'));location.href=`mailto:info@StellarRoutes.com?subject=${subject}&body=${body}`})}
});
